# name: Deploy Azure Resource Group using Terraform

# on:
#   push:
#     branches:
#       - main

# jobs:
#   terraform:
#     runs-on: [self-hosted, ASUS]


#     steps:
#       # Step 1: Checkout the code
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       # Step 2: Setup Terraform
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.5.0

#       # Step 3: Azure Login using Service Principal
#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       # Step 4: Terraform Init
#       - name: Terraform Init
#         run: terraform init

#       # Step 5: Terraform Validate
#       - name: Terraform Validate
#         run: terraform validate

#       # Step 6: Terraform Plan
#       - name: Terraform Plan
#         run: terraform plan -out=tfplan

#       # Step 7: Terraform Apply
#       - name: Terraform Apply
#         run: terraform apply -auto-approve tfplan

